### ISSUE TITLE
Test suite does not compile with aeson-1.2.4.0 (Stackage LTS 11.22)

### ISSUE THREAD

**Issue by skeuchel** [dhall-lang/dhall-json#64]
```
[1 of 1] Compiling Main             ( tasty/Main.hs, dist-ghc/build/tasty/tasty-tmp/Main.o )

tasty/Main.hs:52:19: error:
    Not in scope: ‘Data.Aeson.eitherDecodeFileStrict’
    Perhaps you meant one of these:
      ‘Data.Aeson.eitherDecodeStrict’ (imported from Data.Aeson),
      ‘Data.Aeson.eitherDecodeStrict'’ (imported from Data.Aeson)
    Module ‘Data.Aeson’ does not export ‘eitherDecodeFileStrict’.
```

eitherDecodeFileStrict was added in aeson-1.3.0.0
